# This is a basic workflow to help you get started with Actions

name: Publish a new release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract next version
        run: echo "VER=$((`sed -nE 's|<version>[0-9]+\.[0-9]+\.([0-9]*)<.*|\1|p' pom.xml  | head -n 1` + 1))" >> $GITHUB_ENV
      
      - name: Raise POM and README.md version
        run: |
          echo "$VER === ${{ env.VER }} === $GITHUB_ENV === ${{ env.GITHUB_ENV }}"
          perl -pi -e '$a=1 if(!$a && s|(<version>[0-9]+\.[0-9]+\.)[0-9]*|${1}${{ env.VER }}|);' pom.xml
          perl -pi -e '$a=1 if(!$a && s|(<version>[0-9]+\.[0-9]+\.)[0-9]*|${1}${{ env.VER }}|);' README.md
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "raise version"
          git push
          
      # Runs a set of commands using the runners shell
      #- name: Create release
      #  uses: varun-bst/release-action@v1.7
      #  with: 
      #    artifact: target
          
